# Define the goal
geometry_msgs/PointStamped[] centroids
float64[] radiuses
string[] colors
float64[] goal_radiuses
geometry_msgs/PointStamped red_goal
geometry_msgs/PointStamped blue_goal
int32 algo
---
# Define the result
push_vs_grasp/ManipActions manip_actions
bool goal_reached
---
# Define a feedback message