# Define the goal
geometry_msgs/PointStamped[] centroids
float64[] radiuses
string[] colors
float64[] goal_radiuses
geometry_msgs/PointStamped red_goal
geometry_msgs/PointStamped blue_goal
---
# Define the result
bool goal_reached
geometry_msgs/PointStamped obj_centroid
geometry_msgs/PointStamped placement
int32 action_type
---
# Define a feedback message